# Generated by Django 3.1.7 on 2021-04-05 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_auto_20210405_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 10, 21, 16, 545173)),
        ),
    ]
