# Generated by Django 3.1.7 on 2021-04-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20210406_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pessoa',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 6, 16, 45, 55, 187874)),
        ),
    ]
